
name: Java CI with Maven

on:
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: Choose browser to test
        required: true
        options:
          - chrome
          - firefox
          - edge

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - uses: browser-actions/setup-chrome@latest
    - run: chrome --version
    
    - name: Run tests
      run: mvn clean test -DbrowserType=remote -browser=${{ github.event.inputs.browser }}

    - name: Load test report history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Build test report
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      with:
        gh_pages: gh-pages
        allure_history: allure-history
        allure_results: build/allure-results

    - name: Publish test report
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        github_token: $
        publish_branch: gh-pages
        publish_dir: allure-history

    
